services:
  rabbitmq:
    ports:
      - "15670:15670" # web STOMP examples UI
      - "15672:15672" # main UI
      - "15674:15674" # web STOMP (web sockets)
      - "15692:15692" # prometheus
      - "61613:61613" # stomp

  web:
    volumes:
      - .:/app
    environment:
      - DEBUG=1
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"