services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - DEBUG=0
    env_file:
      - .env
    command: sh -c "python manage.py migrate --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:8000"

  collectstatic:
    build: .
    command: python manage.py collectstatic